# Generated by Django 4.1.7 on 2023-03-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='complement',
            field=models.CharField(max_length=30, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='number',
            field=models.CharField(max_length=5, verbose_name='Número'),
        ),
    ]
