# Generated by Django 4.1.7 on 2023-03-18 01:19

from django.db import migrations, models
import utils.validacpf


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_complement_alter_perfil_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[utils.validacpf.valida_cpf], verbose_name='CPF'),
        ),
    ]
