# Generated by Django 4.1.7 on 2023-02-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('short_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Descrição curta')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='Descrição longa')),
                ('image', models.ImageField(upload_to='products/img/%Y/%b/', verbose_name='Imagem do produto')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('marketing_price', models.FloatField(verbose_name='Preço marketing')),
                ('promotional_marketing_price', models.FloatField(default=0, verbose_name='Preço marketing promocional')),
                ('variation_type', models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1, verbose_name='Tipo')),
            ],
        ),
    ]
