# Generated by Django 4.1.7 on 2023-02-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
