# Generated by Django 4.1.7 on 2023-03-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_produto_short_description_alter_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nome'),
        ),
    ]
