# Generated by Django 4.1.7 on 2023-03-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_variacao_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Nome'),
        ),
    ]
