# Generated by Django 4.1.7 on 2023-02-22 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('A', 'Aprovado'), ('P', 'Pendente'), ('C', 'Criado'), ('R', 'Recusado'), ('E', 'Enviado'), ('F', 'Finalizado')], default='C', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Produto')),
                ('product_id', models.PositiveIntegerField(verbose_name='ID do produto')),
                ('variation', models.CharField(max_length=100, verbose_name='Variação')),
                ('variation_id', models.PositiveIntegerField(verbose_name='ID da variação')),
                ('price', models.FloatField()),
                ('promotional_price', models.FloatField(verbose_name='Preço promocional')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('image', models.CharField(max_length=2000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
    ]
