# Generated by Django 4.1.7 on 2023-03-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_itempedido_image_alter_itempedido_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
